{% set name = "YAML-Tiny" %}
{% set version = "1.76" %}

package:
  name: perl-{{ name|lower }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/E/ET/ETHER/{{ name }}-{{ version }}.tar.gz
  sha256: a8d584394cf069bf8f17cba3dd5099003b097fce316c31fb094f1b1c171c08a3

build:
  number: 0
  noarch: generic
  script:
    - perl Makefile.PL INSTALLDIRS=vendor NO_PERLLOCAL=1 NO_PACKLIST=1
    - make
    - make test
    - make install VERBINST=1

requirements:
  build:
    - make
  host:
    - perl
  run:
    - perl

test:
  imports:
    - YAML::Tiny

about:
  home: https://metacpan.org/release/{{ name }}
  license: GPL-1.0-or-later OR Artistic-1.0-Perl
  license_family: OTHER
  license_file: LICENSE
  summary: Read/Write YAML files with as little code as possible

extra:
  recipe-maintainers:
    - tdegeus
